### ISSUE TITLE
Personal profile 1.2

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#126]
https://www.figma.com/file/UDeXhKfd7BiuWrGfLzoUlpwS/U%C2%B0Community-v.1.2?node-id=1926%3A1

- [x] https://github.com/UOSnetwork/ucom.frontend/issues/132 Test image resize on client (2h)
- [x] https://github.com/UOSnetwork/ucom.frontend/issues/127 User header (8h)
- [x] https://github.com/UOSnetwork/ucom.frontend/issues/128 Sidebar (8h)
- [x] https://github.com/UOSnetwork/ucom.frontend/issues/129 Feed (4h)
- [x] https://github.com/UOSnetwork/ucom.frontend/issues/139 Add share menu (4h) (Only copy link)
- [x] https://github.com/UOSnetwork/ucom.frontend/issues/143 Organization profile (8h)

**Comment by sudokey** [comment]
- [ ] https://github.com/UOSnetwork/ucom.frontend/issues/127
- [ ] https://github.com/UOSnetwork/ucom.frontend/issues/128
- [ ] https://github.com/UOSnetwork/ucom.frontend/issues/129
