### ISSUE TITLE
[16SP-14h, 17SP-21h, 18SP-12h] Picture gallery 

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#157]
Ability to upload multiple pictures at once.
Preview gallery for multiple pictures.
Available in direct posts, comments.

### TODO
- [x] add 'left' and 'right' keyboard keys bindings on gallery scrolling
![image](https://user-images.githubusercontent.com/46528935/57930157-e7864800-78bd-11e9-850a-6be9230c9b75.png)
- [x] add multiple pictures uploading with drag'n'drop
- [x] active preview image (bottom bar) should be always at the center of the page
![image](https://user-images.githubusercontent.com/46528935/57928476-865c7580-78b9-11e9-8c58-6a03bfcfa703.png)
- [x] add an easing (animated appearing) for 'left' and 'right' buttons
![image](https://user-images.githubusercontent.com/46528935/57928626-04b91780-78ba-11e9-99eb-b783380570ce.png)
- [x] fix 1st pic is always opened even if click on another
![image](https://user-images.githubusercontent.com/46528935/57929769-e0ab0580-78bc-11e9-9f43-52daae90e734.png)
- [x] fix console warning (in case of duplicated gifs added by link):
Warning: Encountered two children with the same key
sample post: https://staging.u.community/user/461/14763
![image](https://user-images.githubusercontent.com/46528935/57932548-d3dde000-78c3-11e9-9887-77695111103e.png)
- [x] add preloader to watch the pic uploading progress https://www.figma.com/file/UDeXhKfd7BiuWrGfLzoUlpwS/U%C2%B0Community-v.1.2?node-id=4813%3A167
- [x] fix background blinking on hover on left/right arrows
~~- [ ] remove '+N' badge and display all attached pictures
https://user-images.githubusercontent.com/46528935/57928403-4d240580-78b9-11e9-8140-aca3246537d3.png~~
~~- [ ] __not reproduced__ fix console warnings (duplicated uploaded gifs):
Warning: Failed prop type: The prop `name` is marked as required in `MyUserCard`, but its value is `null`.
Warning: Failed prop type: The prop `rate` is marked as required in `MyUserCard`, but its value is `null`.
sample post: https://staging.u.community/user/461/14760~~
