### ISSUE TITLE
Edit profile 2.0 - Markup

### ISSUE THREAD

**Issue by dimalitvinov** [UOSnetwork/ucom.frontend#168]
8h - markup SP-14
2h - markup SP-15
10h - fix bugs SP-17

https://github.com/UOSnetwork/ucom.frontend/issues/184 - bug with remove social networks need backend fix

### TODO
- [ ] **confirmed** add blank space to the bottom to make 'About Me' and 'Links' section achievable for left navigation menu
- [ ] **confirmed replace '0,5 Mb' with '5 Mb'** replace outdated avatar uploading text "Drag and drop. We support JPG, PNG or GIF files. Max file size 0,5 Mb" (max file size is more than 0,5mb now)
~~- [ ] **declined** drag and drop area is not on the "Drag and drop" text :)~~
- [ ] **confirmed** to strictly mark drag'n'drop area on drag picture into browser window 
![image](https://user-images.githubusercontent.com/46528935/57865026-8ac75680-7805-11e9-8121-c1a0d35dd688.png)
- [ ] **confirmed** remove "Few words..." text ~~different wrapping (on different window widths) and ambiguous closing bracket~~
![image](https://user-images.githubusercontent.com/46528935/57864987-7aaf7700-7805-11e9-84ef-8e7adae05dab.png)
- [ ] **confirmed** fix elements overlapping
![image](https://user-images.githubusercontent.com/46528935/57864868-4c319c00-7805-11e9-8331-bdb7db0b47cd.png)
~~- [ ] **declined** navigation menu slightly changes their position on scroll
https://user-images.githubusercontent.com/46528935/57866193-9ddb2600-7807-11e9-9485-1d761efaf45f.png~~
- [ ] show remove button ("trash bin") on hover on input field only (hide in other cases), align input fields
![image](https://user-images.githubusercontent.com/46528935/57921367-dd584f80-78a5-11e9-8476-b92cd9e347d9.png)

1) подсветить кругляшок аватарки если я сделал драг фотки и переместил в браузер.
2) убрать дескрипшн к редактированию профиля.
3) отступ слева от края попапа до навигации 100пх
4) иконка удаления должна появляться по ховеру на инпут
