### ISSUE TITLE
[40h] FRNT-314 Add Overview page for content

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#23]
- [x] [10h] Community tabs
- [x] [8h] Tags tab
- [x] [1,5h] Tag preview card
- [x] [4h] Community preview card
- [x] [6h] Posts tab
- [x] [2h] Hot, Trending, Fresh, All tabs
- [x] [8h] Publications tab
- [ ] Backend integration #46 
- [x]  shorten tags
- [x]  fix community avatar

https://www.figma.com/file/UDeXhKfd7BiuWrGfLzoUlpwS/U%C2%B0Community-v.1.2?node-id=330%3A0

Add the Overview page, consisting of 4 major categories:
- posts
- publications
- communities
- tags

Each category has built-in prefilters: 
- top
- fresh
- trending
- hot

Each category lists authors of displayed content (users and communities)

Prefilters' logic:
- Top: all content sorted by rating, top first.
- Fresh: all content, sorted by creation date, new first.
- Trending: all content, sorted by rating gain by the end of a given period. 
`rating gain > 0`
`number of upvotes (or number of posts and publications for tags and communities) > 0`
(in order to exclude rating fluctuations related to users' Importance change)
- Hot: all content, sorted by activity index gain by the end of a given period. 
for posts and publications: 
`activity index = 3*[number of comments] + 1.5*[number of reposts] + 1*[number of upvotes/downvotes]>0`
for tags and communities:
`activity index = 1.5*[number of posts] + 3*[number of publications] + 1*[number of followers]>0`
All parameters should be easily changeable.

# Sidebar lists behavior

### `Published by`
1. Take first 50 posts/publications in a given category
1. Get authors of those posts
1. Sort by first post appearance per author, skip duplicates
1. Show first 5, other are displayed by clicking `show more`

### `Included tags`
1. Take first 50 posts/publications in a given category
1. Get tags of those posts
1. Sort by first post appearance per tag, skip duplicates
1. Show first 5, other are displayed by clicking `show more`

### `Communities`
1. Take first 50 posts/publications in a given category
1. Get communities those posts were posted into
1. Sort by first post appearance per community, skip duplicates
1. Show first 5, other are displayed by clicking `show more`

## `Tags`
1. Take first 50 tags in a given category
1. Get top from `top uses by` (should be renamed to `top influencers`) from those tags
1. Sort by first tag appearance per user, skip duplicates
1. Show first 10, other are displayed by clicking `show more`

`top influencers` for each tag are calculated this way: 
1. Get all posts by a given user
1. Get the share of rating each post is contributing to a given tag, i.e. `post rate/number of tags in a post`
1. Sort by first post appearance per user, skip duplicates

## `Communities`
To be described later, after we test the `hot` mechanics. Should be based on user engagement rate in a given community.
ER = Number of posts with ER>0, number of publications with ER>0, number of up/downvotes, number of comments with ER>0, number of reposts with ER>0

**Comment by Sxela** [comment]
<img width="423" alt="screenshot 2019-02-20 at 13 42 23" src="https://user-images.githubusercontent.com/11751592/53086120-85fc4a80-3515-11e9-9a81-05b082d5958f.png">
<img width="423" alt="screenshot 2019-02-20 at 13 42 30" src="https://user-images.githubusercontent.com/11751592/53086121-8694e100-3515-11e9-93a8-bd2996da03d3.png">
<img width="420" alt="screenshot 2019-02-20 at 13 42 36" src="https://user-images.githubusercontent.com/11751592/53086122-8694e100-3515-11e9-829c-214c4a0d8d71.png">
<img width="420" alt="screenshot 2019-02-20 at 13 42 43" src="https://user-images.githubusercontent.com/11751592/53086125-872d7780-3515-11e9-8724-05032aab00a8.png">

**Comment by Sxela** [comment]
Initial release:
keep sidebars for the following pages:
`Posts`, `Publications` (`Trending`, `Hot`, `Top`, `Fresh`):
* `Published by`
* `Communities`

Hide all other sidebars until the latest statistic algorithm is up on backend.
