### ISSUE TITLE
[8h] FRNT-304 Implement new comment design and display logic

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#26]
Implement new comment design and display logic.
Comments grouping and pagination, default number of comments  and replies to display should depend on the context. 
- [x] [8h] #39 input and display reply below previous grouped replies
- [x] [4h] new comment input form 
- [x] [4h] new comment markup
- [x] [40h] #36 comment backend GraphQL integration

**Comment by Yopur** [comment]
It would be nice, if empty spaces and empty paragraphs won't be displayed:
<img width="802" alt="screenshot 2019-01-30 at 20 00 21" src="https://user-images.githubusercontent.com/17730625/51998944-b75f9880-24ca-11e9-9302-731a9dab42d4.png">
