### ISSUE TITLE
Edit profile 2.0 - Validate and saving

### ISSUE THREAD

**Issue by dimalitvinov** [UOSnetwork/ucom.frontend#261]
10h - SP-16 (validate, save)

### TODO
- [ ] error displayed on avatar uploading
- [ ] avatar updating without saving changes (just on uploading)
- [ ] **to discuss** closing without saving?? (especially annoying on click out of pop-up)
