### ISSUE TITLE
[28h] Overview - backend integration

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#46]
- [x] UOSnetwork/ucom.backend#13
- [x] UOSnetwork/ucom.backend#11
- [x] UOSnetwork/ucom.backend#10
- [x] UOSnetwork/ucom.backend#9
- [x] [12h] Researching about integration
- [ ] Additional data from backend #83
