### ISSUE TITLE
Voting for Activity Calculator Nodes

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.frontend#68]
- [x] Desktop: [20h] #123 
- [x] Backend integration: [16h] #124
- [x] Mobile: [12h] #125

Design: https://www.figma.com/file/UDeXhKfd7BiuWrGfLzoUlpwS/U%C2%B0Community-v.1.2?node-id=1617%3A2255

### TODO:
- [x] "Block Producers to Unvote" section is always empty - **(expecting backend)**
- [x] "Votes" column name trimmed to "VOT..."
- [x] "Vote Amount" column values don't fit column width (to extend the width or add a hint on hover)
- [x] "State" column values aligned different
- [x] "Backup" state trimmed to "Back..."
- [x] fix Governance page shouldn't displayed with no data
https://user-images.githubusercontent.com/46528935/57377483-43105180-71ab-11e9-89d4-7308605c1a36.png
- [x] replace "," delimiter with " " (space)
https://user-images.githubusercontent.com/46528935/57379256-40aff680-71af-11e9-85a6-fa121b05a153.png
- [x] add highlight on hover for each table
- [x] hide 1st column if no data displayed
https://user-images.githubusercontent.com/46528935/57366021-d5eec300-718e-11e9-8e93-9075556b67fd.png
- [x] round Voting Power to integer
https://user-images.githubusercontent.com/46528935/57365982-c4a5b680-718e-11e9-8c6f-a9e577932649.png
https://user-images.githubusercontent.com/46528935/57366203-30881f00-718f-11e9-8b9a-4f493d9db355.png
- [x] right align Vote amount column (single baseline for both title and content)
https://user-images.githubusercontent.com/46528935/57365459-c622af00-718d-11e9-8e40-87275518a717.png
- [x] left align State column
https://user-images.githubusercontent.com/46528935/57365426-b905c000-718d-11e9-81bf-90ae89291462.png
- [x] fix both header and sub-header displayed in multiple lines (window width ~=770px)
![image](https://user-images.githubusercontent.com/46528935/57622451-45e9b880-7596-11e9-96a7-676540cd3aaf.png)
~~- [ ] increase width for "Active" state badge (exact to "Backup" badge width)
https://user-images.githubusercontent.com/46528935/57365410-ac816780-718d-11e9-95d4-98356017b151.png~~
~~- [ ] stretch Vote Amount column (to avoid ellipsis)
https://user-images.githubusercontent.com/46528935/57365487-d2a70780-718d-11e9-9cac-a560bb4820d9.png~~

### Block Producer Election pop-up:
- [x] check font weight
https://user-images.githubusercontent.com/46528935/57366791-68439680-7190-11e9-9df6-67b3819ad0af.png
- [x] fix VOTES title
https://user-images.githubusercontent.com/46528935/57365116-25cc8a80-718d-11e9-9091-6ad8915ce890.png
- [x] fix table aligning
https://user-images.githubusercontent.com/46528935/57365384-9f647880-718d-11e9-9204-031bab24c039.png
- [x] remove redundant 'X' button
https://user-images.githubusercontent.com/46528935/57365766-5fea5c00-718e-11e9-9cc8-9a62e068f503.png
- [x] closing "Vote for these producers" pop-up should return to "Block Producer Election" pop-up, not Governance page
~~- [ ] align "Cast your vote" button
https://user-images.githubusercontent.com/46528935/57365286-6e844380-718d-11e9-8d07-08ef376a91a0.png~~

### Mobile Markup
- [x] fix 'X' place
https://user-images.githubusercontent.com/46528935/57366948-bc4e7b00-7190-11e9-8742-407636db56c2.png
- [x] increase footer padding
https://user-images.githubusercontent.com/46528935/57367047-f3bd2780-7190-11e9-9f17-06287944ecb5.png
- [x] increase padding and fix aligning
https://user-images.githubusercontent.com/46528935/57367174-2bc46a80-7191-11e9-8002-dfb0588ac27e.png
- [x] fix column titles in multiple lines
- [x] fix different left and right paddings for both header ant table
![image](https://user-images.githubusercontent.com/46528935/57623167-e2608a80-7597-11e9-8074-35c5b684bb4c.png)
